### ISSUE TITLE
Special clause content

### ISSUE THREAD

**Issue by TomTomRixRix** [douira/resolution-editor#104]
At the moment there are two small features that the editor doesn't support yet. They're not super important, however, it would be nice if the editor could parse and render them correctly. They won't be used often but sometimes they are necessary for the debate.

1. Molecular formulas like H<sub>2</sub>0, CO<sub>2</sub> or O<sub>3</sub> need sub and super script support. 
2. Resolution names like *A/RES/69/154* or document names like the *UNESCO  Declaration  concerning 
the  Intentional Destruction  of  Cultural  Heritage*

Perhaps we could simply support this by using the markdown or HTML syntax and replace it during the rendering process?

**Comment by douira** [comment]
Will add these features in #95. Does Latex support rendering markdown through some plugin or extension? The markdown syntax is simple enough that most people should be able to use it. But I don't trust delegates to correctly open the sub and sup tags...
We can also create a custom parser that only support a few limited syntax set. For example:
- Subscript: `H_2O` renders as H<sub>2</sub>O
- Superscript: `x^3` renders as x<sup>3</sup>
Both of these only affect the next character.
- Italics: (like in Markdown) `*blah*` renders as *blah*
The editor will make clauses with an uneven number of asterisks invalid. We'll just have to accept that no asterisks will be used in a normal text if we use single ones (Escaping is too much of a hustle). We could also only see the double asterisks as italics markers if the use of asterisks is common.

**Comment by douira** [comment]
Can you provide the necessary LaTeX commands that the render code generator should insert around the marked strings? The JS can take care of parsing the clauses.

**Comment by TomTomRixRix** [comment]
The LaTeX comands are quite intuitive, at least for tech people:
- sub scripts are achieved by simply putting an underscore before the character. So is would be `H_2O`. When there is more than one character that should be put into the subscript than on needs a curly brackets: `C_6H_{12}O_6`.
- same for super scripts: there you need a circumflex character `x^2`
- for italics you could use `\textit{youritalictext}` or what I would prefer `\emph{youritalictext}`

**Comment by TomTomRixRix** [comment]
So hopefully only the three characters _^* need to be parsed and correctly replaced be the JS layer.

**Comment by TomTomRixRix** [comment]
Actually there seems to be a markdown package for LaTeX: https://ctan.org/pkg/markdown
But I've never used it before and thus can't say how handy it is. And I believe that using Markdown in LaTeX is not what we should aim for since we should focus on one syntax for setting our text.

**Comment by douira** [comment]
### Yeah, let's just use a custom parser.
But I think for several characters in sub or superscript using brackets is too complicated and too hard for users to use. Maybe just repeat the `_` or `^` for every affected character? For example: `C_6H_1_2O_6` becomes C<sub>6</sub>H<sub>12</sub>O<sub>6</sub>
### Alternative:
Use an ending character to end the sub-/superscript: 
`C_6H_12|O_6` becomes C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> where `|` stops the subscript. If no `|` is present after the `_` only one character will be affected.
This is all analog with the superscript `^`.

I don't know which one would be easier to use...

**Comment by douira** [comment]
This is quite ok: https://regex101.com/r/Du9Gfb/1

**Comment by douira** [comment]
Managed to do all of this with regexp! Yay

**Comment by douira** [comment]
Using `_` makes it very unhappy and produces lots of errors.

**Comment by TomTomRixRix** [comment]
Hm, that's strange. Do you have any Error Messages or the LaTeX Code? Then I can have a look what might be the problem

**Comment by TomTomRixRix** [comment]
I've got an idea why it crashes. For `_` and `^` you need to be in a math environment in LaTeX otherwise it won't understand what to do with these characters. To get into an inline math environment you can use the Dollar character like this: `H$_2$O` or `C$_6$H$_1$$_2$O$_6$`. Same with super scripts.

`\emph` is working in normal text mode though.

**Comment by douira** [comment]
solved in #95
