### ISSUE TITLE
'Co-Sponsors' and 'Question of' overflow out of document

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#113]
See this: 
![screen shot 2018-01-29 at 17 22 37](https://user-images.githubusercontent.com/17120022/35521104-34a08494-0519-11e8-9f31-95fd1f633998.png)
The text should wrap properly because it is realistically possible to have a long value in either of these fields. @TomTomRixRix

**Comment by TomTomRixRix** [comment]
Will fix it soon so that it looks like this :smile::
![grafik](https://user-images.githubusercontent.com/13121269/37160513-b2eac0ae-22f0-11e8-983f-c2a44a2beb93.png)

**Comment by TomTomRixRix** [comment]
Should be fixes with commit 6ce34a8c6b8c932303a45bad49de80fed614bb6b
