### ISSUE TITLE
Resolution Booklet Renderer

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#127]
Renderer for the resolution Booklet.
- First cover page with munol logo image, title (determined from input on resolution booklet page) and signatures.
  - signature: signature image with name and position
  - number of signatures is undetermined and have to arranged in a nice grid layout on the cover page
  - gets input list of signature entities on resolution booklet page when ready to generate pdf
  - signature images have to inserted if necessary, maybe use https://github.com/szimek/signature_pad
- continuous page numbers but new page for every resolution
- resolution booklet is stapled and left and right margins/pages have to be adjusted accordingly (printed double sided)
- renderer inserts correct forum and sponsor when rendering booklet

**Comment by TomTomRixRix** [comment]
# Current Titlepage
![grafik](https://user-images.githubusercontent.com/13121269/37567991-472022e2-2acf-11e8-9739-e1a622ced2e9.png)

# Current Reso Booklet pages
![grafik](https://user-images.githubusercontent.com/13121269/37568005-7015258a-2acf-11e8-9a81-f8ec1833f16e.png)

**Comment by TomTomRixRix** [comment]
I've made a new branch `reso-booklet` and copied the old `template.latex` and `generatePdf.js` file to new files `booklet-template.latex` and `gernerateBookletPdf.js`. The latter contains the `function generateLatexBooklet(booklet){...` which is basically a wrapper of the old `generateLatex(resDoc){...` function. 

A big difference is however, that now a booklet object is passed which has:
* a `title`, e.g. `Resolution Booklet`
* a `session` e.g. `XXI Annual Session`
* a list of 7 or 8 `signatures` which themselves contain:
   * a `name` e.g. `Leonard Roemer`
   * a `position` e.g. `Secretary-General`
* a list of `resolutions` which are like the `resDoc` object used before.

All this information has to be set somewhere and needs to be passed when calling `generateLatexBooklet()`

**Comment by douira** [comment]
Let's move this conversation over to the PR of this topic: #137

**Comment by douira** [comment]
Renderer seems to be more or less done. testing and probably some changes are needed though.
