### ISSUE TITLE
Special Syntax is broken again

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#173]
Gives an error along these lines for all three types of special syntax formatting:
````
Argument of \@xs@StrBehind has an extra }.
<inserted text> 
                \par 
l.69 ... concerned}{fdsfsdfsdfs gd\emph{jjghjhg},}
\end{preamb}\vspace{-12pt}...\nNo pages of output.
```

**Comment by douira** [comment]
There are also lines with `\StrLeft` and `\StrBehind` which I think were meant for selective capitalization. Do we still need those? As far as I know, the generator js code handles capitalization, and if not it would be easier to implement there.

**Comment by TomTomRixRix** [comment]
That's true, we can completly strike out these three lines and use 
`\emph{#1}
#2%`
and 
`\underline{\smash{#1}}
#2%`

**Comment by douira** [comment]
can you apply these changes in the pm or a new branch?
