### ISSUE TITLE
PDF loads from cache

### ISSUE THREAD

**Issue by LeoRoe** [douira/resolution-editor#185]
When clicking on "View PDF" and then on "here", the cached version of the PDF may be loaded. You cannot be sure, that delegates understand, that they have to reload the page.

Suggested solution: Add a "?z=234" with 234 being a random number after the link, e.g. http://intern.tms-hl.org:3000/rendered/@VX6D23TB.pdf?z=234 . The random number should be re-generated, whenever "View PDF" is clicked.

**Comment by douira** [comment]
This is related to #178

**Comment by douira** [comment]
Simple cache bust like this has been implemented for a while. Seems to work fine for now until #178 is implemented and this may be changed (or not).
