### ISSUE TITLE
wrong indentation of OC starting phrases higher than 9

### ISSUE THREAD

**Issue by TomTomRixRix** [douira/resolution-editor#195]
From the 10th OC onwards there is one whitespace too much before the starting phrase. This can be fixed by setting the `leftmargin =2cm` to a specific value instead of `*` in the `\begin{enumerate}[1., ` of the OCs.

**Comment by douira** [comment]
I think this is done now? Correct me if this is wrong

**Comment by TomTomRixRix** [comment]
Yes, we fixed this somehow, but I'm not sure how we did it :smile:
