### ISSUE TITLE
EABs duplicate with file load after touching elements

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#22]
After touching some elements (clicking) so that they display EABs, loading a file causes the EABs to be duplicated many times. (not all over though)

**Comment by douira** [comment]
I can't reproduce this anymore (on latest dev branch). Please, somebody, check this. @TomTomRixRix

**Comment by TomTomRixRix** [comment]
I'm not sure, what the concrete bug was, but I don't get this bug. Might be fixed already :smile:

**Comment by douira** [comment]
ok, closing this. We'll have to investigate if this pops up again.
