### ISSUE TITLE
File read error

### ISSUE THREAD

**Issue by NiJoMa** [douira/resolution-editor#24]
Ich weiß nicht ob der Fehler bekannt bzw. die Funktion schon vorhanden ist... Leider funktioniert das herunterladen und erneute einlesen der Resolutionen noch nicht.
(I do not know whether the error is known or the function exists at all yet ... Unfortunately, the download and upload of the same file does not yet work.)

**Comment by douira** [comment]
Welchen Browser und Betriebssystem benutzt du?

**Comment by NiJoMa** [comment]
Win 7 Home Premium Service Pack 1; Browser Chrome;
Der Inhalt der heruntergeladenen .rso datei sieht intakt aus:
{
  "magic": "PG52QE1AM4LACMX9",
  "version": 1,
  "status": {
    "editied": 1504387805058,
    "author": "Germany"
  },
  "resolution": {
    "address": {
      "forum": "1st Commitee",
      "questionOf": "sddsdas",
      "sponsor": {
        "main": "United States of America",
        "co": [
          "Placeholder Coutry"
        ]
      }
    },
    "clauses": {
      "preambulatory": [
        {
          "content": "all factd",
          "phrase": "Notices"
        }
      ],
      "operative": []
    }
  }
}
Leider könnte die Datei aber beim hochladen nicht eingelesen werden

**Comment by douira** [comment]
Guck ich mir mal an

**Comment by douira** [comment]
Try it with the branch (fix-upload) #30 is pulling or wait for it to be merged and then test again. File loading seems to work ok now.

**Comment by douira** [comment]
I'm closing this now because it looks like this bug is solved. We can investigate further if it pops up again.
