### ISSUE TITLE
Fix spacing in generated PDF

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#48]
pandoc or something in between seems to mess with the spacing.

**Comment by TomTomRixRix** [comment]
this should be fixes by #93

**Comment by douira** [comment]
Doesn't seem to be completely fixed... 
![screen shot 2017-11-26 at 17 35 47](https://user-images.githubusercontent.com/17120022/33242127-44e4db96-d2d0-11e7-9b4e-c695a815785a.png)

**Comment by douira** [comment]
Seems to be fixed
