### ISSUE TITLE
Autofill data without spaces

### ISSUE THREAD

**Issue by TomTomRixRix** [douira/resolution-editor#64]
Same of the auto filled data is a bit broken. I guess it's just the spaces between two word that are not displayed correctly. For example "Amnesty International" is displayed as "AmnestyInternational".

**Comment by douira** [comment]
Will investigate soon.

**Comment by douira** [comment]
Noticed that sponsors with spaces are marked invalid in the chips list because the space is missing.

**Comment by douira** [comment]
I just noticed that this is still happening even after adding the spaces in autofillData.json.
![screen shot 2017-11-20 at 18 52 45](https://user-images.githubusercontent.com/17120022/33033383-7e2e1652-ce24-11e7-9018-ba72531af97d.png) (checked on a stage 0 resolution in the change-actions branch now.)

**Comment by douira** [comment]
Clarification: There is actually a feature that prevents the cosponsors from containing the main sponsor. This is what was triggering this. The issue with the spacing seems to have been fixed though.
